stages:
  - publish

publish:
  stage: publish
  image: ghcr.io/sensmetry/sysand:0.1.0-rc.1
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sysand
  variables:
    SYSAND_INDEX_URL: https://staging.sysand.com
  script:
    # acquire and configure sysand index credentials
    - |
      TOKEN=$(
        curl -s -X POST "${SYSAND_INDEX_URL}/api/v1/oidc/token" \
          -H "Content-Type: application/json" \
          -d "{\"token\": \"${GITLAB_OIDC_TOKEN}\"}" \
        | grep -o '"token": *"[^"]*"' \
        | cut -d'"' -f4 \
      )
      export SYSAND_CRED_X="${SYSAND_INDEX_URL}/api/v1/**"
      export SYSAND_CRED_X_BEARER_TOKEN="$TOKEN"

    # initialize dummy project
    - |
      sysand init --publisher Admin --name proj0 --license MIT --version "2.0.$(date +%s)"
      sysand info metamodel --set sysml

      cat > README.md << 'EOF'
      # Project README

      This is a Markdown `test` string used to verify `sysand` packaging.
      EOF

      mkdir LICENSES
      cat > LICENSES/MIT.txt << 'EOF'
      MIT License

      Dummy content.
      EOF

    # build and publish a project to the index
    - |
      sysand build
      sysand publish --index "${SYSAND_INDEX_URL}"
